#include "game/pages/street_view.h"

namespace
{

constexpr int mapHeightFromWidth(const int mapWidth)
{
    return mapWidth * 3 / 4;
}

constexpr short int START_MAP_WIDTH = 400;
constexpr short int START_MAP_HEIGHT = mapHeightFromWidth(START_MAP_WIDTH);

constexpr short int MAP_X_INCR = 150;
constexpr short int MAP_Y_INCR = mapHeightFromWidth(MAP_X_INCR);

constexpr double MIN_MAP_WIDTH_RATIO = 2.0 / 10.0;
constexpr double MAX_MAP_WIDTH_RATIO = 6.0 / 10.0;

}

namespace game::pages
{

StreetViewPage::StreetViewPage(QWidget* parent, const geo::Location& mapCenter)
    : QFrame(parent)
    , m_streetView(this)
    , m_interactiveMap(this, mapCenter)
    , m_returnToStartButton("Return to start", this)
    , m_guessButton("Guess", this)
    , m_shrinkMapButton("-", this)
    , m_enlargeMapButton("+", this)
{
    setContentsMargins(0, 0, 0, 0);

    m_streetView.setGeometry(rect());
    m_interactiveMap.setFixedSize(START_MAP_WIDTH, START_MAP_HEIGHT);
    m_guessButton.setMinimumSize(150, 40);
    m_returnToStartButton.setMinimumSize(150, 40);
    m_shrinkMapButton.setFixedSize(30, 30);
    m_enlargeMapButton.setFixedSize(30, 30);

    m_guessButton.setEnabled(false);

    connect(&m_interactiveMap, &sv::InteractiveMap::guessMarkerPlaced, this, &StreetViewPage::onGuessMarkerPlaced);
    connect(&m_guessButton, &QPushButton::clicked, this, &StreetViewPage::onGuessButtonClicked);
    connect(&m_returnToStartButton, &QPushButton::clicked, this, &StreetViewPage::onReturnToStartButtonClicked);
    connect(&m_shrinkMapButton, &QPushButton::clicked, this, &StreetViewPage::onShrinkMapButtonClicked);
    connect(&m_enlargeMapButton, &QPushButton::clicked, this, &StreetViewPage::onEnlargeMapButtonClicked);
}

const geo::Location& StreetViewPage::getStreetViewLocation() const
{
    return m_streetView.getLocation();
}

void StreetViewPage::startNewRound(const geo::Location& location)
{
    m_streetView.setLocation(location);
    m_interactiveMap.removeLocationMarker();
    m_guessButton.setEnabled(false);
}

void StreetViewPage::showEvent(QShowEvent *event)
{
    updateMapRatios();
    QFrame::showEvent(event);
}

void StreetViewPage::resizeEvent(QResizeEvent* event)
{
    QFrame::resizeEvent(event);

    resizeStreetView();
    resizeAndMoveMap();
    moveMapSizeButtons();
    moveFunctionalButtons();
}

void StreetViewPage::resizeStreetView()
{
    m_streetView.resize(width(), height());
}

void StreetViewPage::resizeAndMoveMap(int newWidth /*= 0*/, int newHeight /*= 0*/)
{
    const bool isAutoGeneratedSize = newWidth == 0 || newHeight == 0;
    if (isAutoGeneratedSize)
    {
        newWidth = static_cast<int>(m_mapToWindowWidthRatio * width());
        newHeight = mapHeightFromWidth(newWidth);
    }

    m_interactiveMap.setFixedSize(newWidth, newHeight);

    m_interactiveMap.move(width() - m_interactiveMap.width() - 10,
                        height() - m_interactiveMap.height() - 50);

    if (!isAutoGeneratedSize)
        updateMapRatios();
}

void StreetViewPage::moveMapSizeButtons()
{
    m_enlargeMapButton.move(
        m_interactiveMap.x() + m_interactiveMap.width() - m_enlargeMapButton.width() - 5,
        m_interactiveMap.y() + m_interactiveMap.height() - m_enlargeMapButton.height() - 5
    );

    m_shrinkMapButton.move(
        m_enlargeMapButton.x() - m_shrinkMapButton.width() - 5,
        m_enlargeMapButton.y()
    );
}

void StreetViewPage::moveFunctionalButtons()
{
    m_guessButton.move(
        m_interactiveMap.x() + m_interactiveMap.width() - m_guessButton.width(),
        m_interactiveMap.y() + m_interactiveMap.height() + 5
    );

    m_returnToStartButton.move(
        m_guessButton.x() - m_returnToStartButton.width() - 10,
        m_guessButton.y()
    );
}

void StreetViewPage::updateMapRatios()
{
    double mapWidth = m_interactiveMap.width() != 0 ? m_interactiveMap.width() : START_MAP_WIDTH;
    m_mapToWindowWidthRatio = mapWidth / width();
}

void StreetViewPage::setMapSizeButtonsEnabledState()
{
    const bool canShrink = m_mapToWindowWidthRatio > MIN_MAP_WIDTH_RATIO;
    const bool canEnlarge = m_mapToWindowWidthRatio < MAX_MAP_WIDTH_RATIO;

    m_shrinkMapButton.setEnabled(canShrink);
    m_enlargeMapButton.setEnabled(canEnlarge);
}

void StreetViewPage::onGuessMarkerPlaced()
{
    m_guessButton.setEnabled(true);
}

void StreetViewPage::onGuessButtonClicked()
{
    const auto& guessedLocation = m_interactiveMap.currLocation();
    assert(guessedLocation);

    emit guessMade(*guessedLocation);
}

void StreetViewPage::onReturnToStartButtonClicked()
{
    m_streetView.returnToStart();
}

void StreetViewPage::onShrinkMapButtonClicked()
{
    const auto newWidth = m_interactiveMap.width() - MAP_X_INCR;
    const auto newHeight = m_interactiveMap.height() - MAP_Y_INCR;

    resizeAndMoveMap(newWidth,  newHeight);
    setMapSizeButtonsEnabledState();
}

void StreetViewPage::onEnlargeMapButtonClicked()
{
    const auto newWidth = m_interactiveMap.width() + MAP_X_INCR;
    const auto newHeight = m_interactiveMap.height() + MAP_Y_INCR;

    resizeAndMoveMap(newWidth,  newHeight);
    setMapSizeButtonsEnabledState();
}

}