#include "ui/pages/gameplay.h"

#include <QMessageBox>

#include "ui/google/interactive_map.h"
#include "ui/google/streetview.h"

namespace
{

constexpr int mapHeightFromWidth(const int mapWidth)
{
    return mapWidth * 3 / 4;
}

constexpr int START_MAP_WIDTH = 400;
constexpr int START_MAP_HEIGHT = mapHeightFromWidth(START_MAP_WIDTH);

constexpr int MAP_X_INCR = 150;
constexpr int MAP_Y_INCR = mapHeightFromWidth(MAP_X_INCR);

constexpr double MIN_MAP_WIDTH_RATIO = 2.0 / 10.0;
constexpr double MAX_MAP_WIDTH_RATIO = 6.0 / 10.0;

}

namespace ui::pages
{

// ReSharper disable CppMemberFunctionMayBeConst

GameplayPage::GameplayPage(QWidget* parent)
    : QFrame(parent) { }

const geo::Point& GameplayPage::getStreetViewLocation() const
{
    if (!m_streetView)
    {
        assert(!"Street View not initialized yet");

        static const geo::Point emptyPoint;
        return emptyPoint;
    }

    return m_streetView->getLocation();
}

void GameplayPage::startNextRound(const geo::Point& location)
{
    ensureInitialized();

    m_streetView->setLocation(location);
    m_interactiveMap->removeLocationMarker();
    m_guessButton->setEnabled(false);
}

void GameplayPage::setMapCenter(const geo::Point& center)
{
    m_mapCenter = center;

    if (m_interactiveMap)
        m_interactiveMap->setCenter(m_mapCenter);
}

void GameplayPage::showEvent(QShowEvent *event)
{
    updateMapRatios();
    QFrame::showEvent(event);
}

void GameplayPage::resizeEvent(QResizeEvent* event)
{
    QFrame::resizeEvent(event);
    resize();
}

void GameplayPage::ensureInitialized()
{
    if (m_initialized)
        return;

    m_streetView = new google::StreetView(this);
    m_interactiveMap = new google::InteractiveMap(this);
    m_returnToStartButton = new QPushButton("Return to start", this);
    m_guessButton = new QPushButton("Guess", this);
    m_shrinkMapButton = new QPushButton("-", this);
    m_enlargeMapButton = new QPushButton("+", this);

    setContentsMargins(0, 0, 0, 0);

    m_streetView->setGeometry(rect());
    m_interactiveMap->setFixedSize(START_MAP_WIDTH, START_MAP_HEIGHT);
    m_guessButton->setMinimumSize(150, 40);
    m_returnToStartButton->setMinimumSize(150, 40);
    m_shrinkMapButton->setFixedSize(30, 30);
    m_enlargeMapButton->setFixedSize(30, 30);

    m_guessButton->setEnabled(false);

    connect(m_interactiveMap, &google::InteractiveMap::guessMarkerPlaced, this, &GameplayPage::onGuessMarkerPlaced);
    connect(m_guessButton, &QPushButton::clicked, this, &GameplayPage::onGuessButtonClicked);
    connect(m_returnToStartButton, &QPushButton::clicked, this, &GameplayPage::onReturnToStartButtonClicked);
    connect(m_shrinkMapButton, &QPushButton::clicked, this, &GameplayPage::onShrinkMapButtonClicked);
    connect(m_enlargeMapButton, &QPushButton::clicked, this, &GameplayPage::onEnlargeMapButtonClicked);

    if (m_mapCenter != geo::Point{})
        m_interactiveMap->setCenter(m_mapCenter);

    m_initialized = true;
    resize();
}

void GameplayPage::resize()
{
    resizeStreetView();
    resizeAndMoveMap();
    moveMapSizeButtons();
    moveFunctionalButtons();
}

void GameplayPage::resizeStreetView()
{
    if (m_streetView)
        m_streetView->resize(width(), height());
}

void GameplayPage::resizeAndMoveMap(int newWidth /*= 0*/, int newHeight /*= 0*/)
{
    if (!m_initialized)
        return;

    const bool isAutoGeneratedSize = newWidth == 0 || newHeight == 0;
    if (isAutoGeneratedSize)
    {
        newWidth = static_cast<int>(m_mapToWindowWidthRatio * width());
        newHeight = mapHeightFromWidth(newWidth);
    }

    m_interactiveMap->setFixedSize(newWidth, newHeight);

    m_interactiveMap->move(width() - m_interactiveMap->width() - 10,
                        height() - m_interactiveMap->height() - 50);

    if (!isAutoGeneratedSize)
        updateMapRatios();
}

void GameplayPage::moveMapSizeButtons()
{
    if (!m_initialized)
        return;

    m_enlargeMapButton->move(
        m_interactiveMap->x() + m_interactiveMap->width() - m_enlargeMapButton->width() - 5,
        m_interactiveMap->y() + m_interactiveMap->height() - m_enlargeMapButton->height() - 5
    );

    m_shrinkMapButton->move(
        m_enlargeMapButton->x() - m_shrinkMapButton->width() - 5,
        m_enlargeMapButton->y()
    );
}

void GameplayPage::moveFunctionalButtons()
{
    if (!m_initialized)
        return;

    m_guessButton->move(
        m_interactiveMap->x() + m_interactiveMap->width() - m_guessButton->width(),
        m_interactiveMap->y() + m_interactiveMap->height() + 5
    );

    m_returnToStartButton->move(
        m_guessButton->x() - m_returnToStartButton->width() - 10,
        m_guessButton->y()
    );
}

void GameplayPage::updateMapRatios()
{
    if (!m_initialized)
        return;

    const double mapWidth = m_interactiveMap->width() != 0 ? m_interactiveMap->width() : START_MAP_WIDTH;
    m_mapToWindowWidthRatio = mapWidth / width();
}

void GameplayPage::setMapSizeButtonsEnabledState()
{
    const bool canShrink = m_mapToWindowWidthRatio > MIN_MAP_WIDTH_RATIO;
    const bool canEnlarge = m_mapToWindowWidthRatio < MAX_MAP_WIDTH_RATIO;

    m_shrinkMapButton->setEnabled(canShrink);
    m_enlargeMapButton->setEnabled(canEnlarge);
}

void GameplayPage::onGuessMarkerPlaced()
{
    m_guessButton->setEnabled(true);
}

void GameplayPage::onGuessButtonClicked()
{
    const auto& guessedLocation = m_interactiveMap->currLocation();
    assert(guessedLocation);

    emit guessMade(*guessedLocation);
}

void GameplayPage::onReturnToStartButtonClicked()
{
    m_streetView->returnToStart();
}

void GameplayPage::onShrinkMapButtonClicked()
{
    const auto newWidth = m_interactiveMap->width() - MAP_X_INCR;
    const auto newHeight = m_interactiveMap->height() - MAP_Y_INCR;

    resizeAndMoveMap(newWidth,  newHeight);
    setMapSizeButtonsEnabledState();
}

void GameplayPage::onEnlargeMapButtonClicked()
{
    const auto newWidth = m_interactiveMap->width() + MAP_X_INCR;
    const auto newHeight = m_interactiveMap->height() + MAP_Y_INCR;

    resizeAndMoveMap(newWidth,  newHeight);
    setMapSizeButtonsEnabledState();
}

// ReSharper restore CppMemberFunctionMayBeConst

}